#!/bin/sh

# dirs shortcuts
alias \
	d="cd ~/Scrivania && ls" \
	D="cd ~/Scaricati && ls" \
	V="cd ~/Video && ls" \
	h="cd ~/ && ls" \

# files shortcuts
alias \
	zrc="nvim ~/.zshrc" \
	arc="nvim ~/.config/aliasrc" \
	src="nvim ~/.config/shortcutrc" \
	vrc="nvim ~/.config/nvim/init.vim"
